Second Test done
RLazd/home-exercises-2022 pull request #12
Opened 2022-10-14 17:56 UTC by RLazd

2022-10-15 18:38 UTC, janistumpelis requested changes
Kopumā ļoti labi, jāpielabo tikai pāris sīkumi.

2022-10-15 18:38 UTC, janistumpelis commented on majasdarbi/src/main/java/io/codelex/secondTest/exercise1/Card.java
> +    public void validateCCV(String code) {
Validācija uzdevumā prasīta nebija, aprakstā minētais "three digit number but it can start with 0, 045 for example" ir lai paskaidrotu kādā formātā ir dati un lai jūs izvēlētos korektu tipu (konkrēti, lai jūs nepaņemtu int), bet validācija nebija vajadzīga.

2022-10-15 18:38 UTC, janistumpelis commented on majasdarbi/src/main/java/io/codelex/secondTest/exercise2/Basket.java
> +    int basketCurrentSize;
Teorētiski bez šī mainīgā var iztikt, jo pietiktu, ja pārbaudītu tikai list size, bet ja atstātj, tad mainīgajam obligāti jābūt privātam, lai to nevarētu rediģēt no ārpuses, kā arī List jābūt privātam.

2022-10-15 18:38 UTC, janistumpelis commented on majasdarbi/src/main/java/io/codelex/secondTest/exercise2/Basket.java
> +    public Basket(int basketCurrentSize) {
Manuprāt, nav korekti, ka konstruktorā padot current size. Šādi sanāk, ka var izveidot grozu kuram padod 10, pēc tam tajā ieliek 2 lietas un tad kopskaits ir 12, bet listā reāli ir tikai 2 lietas.

2022-10-15 18:38 UTC, janistumpelis commented on majasdarbi/src/main/java/io/codelex/secondTest/exercise3/Joiner.java
> +    public Joiner(String separator, BiFunction functionToMakeString) {
Jā nu šeit no konstruktora būtu jāņem ārā tā funkcija, jo uzdevumā bija prasīts, ka konstruktors saņem tikai separator un join metode saņem tikai T... objects. Kā arī rezultāts Tev nedaudz atšķiras no uzdevumā minētā - Tev sanāk testā "1-2-3-4-", bet būtu jābūt "1-2-3-4".

2022-10-15 18:38 UTC, janistumpelis commented on majasdarbi/src/main/java/io/codelex/secondTest/exercise5/exercise5.java
> +public class exercise5 {
Klase ar mazo burtu.

2022-10-17 07:58 UTC, RLazd commented on majasdarbi/src/main/java/io/codelex/secondTest/exercise3/Joiner.java
> +    public Joiner(String separator, BiFunction functionToMakeString) {
Jā, nepareizi sapratu uzdevumu. Te bija jāpraktizē streams...

2022-10-19 08:49 UTC, janistumpelis commented on majasdarbi/src/main/java/io/codelex/secondTest/exercise1/CreditCard.java
> +        if (balance.subtract(value).compareTo(BigDecimal.ZERO) == 0) {
Te ir maza kļūdiņa - ja salīdzini compareTo rezultātu ar 0, tas nozīmē, ka tas izpildās tikai, tad ja abi mainīgie ir vienādi. Jebšu not enough funds kļūdu izmetīs tikai tad, ja kartē būs 100 EUR un centīsies izņemt 100EUR, bet faktiski tad jau vēl vajadzētu izņemt. Bet ja ņemtu ārā 101, tad jābūt kļudai. (Tas pats arī DebitCard metodei spend money)

Bet pull-requestam likšu approve, tā kā kad šo pielabo vari taisīt merge.

2022-10-19 08:49 UTC, janistumpelis approved these changes

2022-10-20 06:02 UTC, merged